# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect and rewrite rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist"
  functions = "netlify/functions"
